### ISSUE TITLE
yank only sees the first page

### ISSUE THREAD

**Issue by bogolisk** [mptre/yank#41] opened 2018-04-08 13:51 UTC
When using long input such as

    history | yank

yank only sees the 1st page

**Comment by mptre** [comment] 2018-04-09 16:22
This is a known limitation and I do unfortunately not have the time or
motivation to work on this for now. yank is intended to use for rather
small input (i.e. less than `$COLUMNS*$LINES` bytes). When dealing
with potentially large input, I often try to limit it whenever possible.
An example is this mapping to open a URL from an email inside my MUA
(mutt). It works surprisingly well:

```
macro pager \cb \
  "<pipe-message>grep http | yank -d '()<>\" ' | xargs -r firefox -new-tab<Return>" \
  'open URL'
```

Taking the opportunity for some self-promotion: [pick] could be an
alternative when pre-filtering is not possible (I'm a maintainer of this
utility as well). You could even filter using pick first and the use
yank to select a field:

```sh
$ pick <large-file | yank
```

Closing this for now. I'd be happy to review patches adding support for
scrolling.

[pick]: https://github.com/calleerlandsson/pick

**Closed as completed by mptre** 2018-04-09 16:22 UTC

**Comment by mohannad-abwah** [comment] 2024-01-16 04:21
@mptre Thanks for the response explaining the current state. That's totally fair.

A small request, if I may, is to just keep this issue open since it isn't resolved and could serve for inspiration for others potentially looking to contribute. This is additionally confusing since the issue is closed as `completed`. It also leads to duplicates being open instead of adding & reinforcing an issue.
